# Generated by Django 4.0.3 on 2022-03-24 13:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_code_alter_auth_my_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='invite_code',
            field=models.CharField(default='NULL', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default='tcudM2', max_length=6),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.IntegerField(validators=[main.models.Code.validate_code]),
        ),
    ]
