# Generated by Django 4.0.3 on 2022-03-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_auth_my_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='invite_code',
        ),
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default='6vPyqD', max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=6)),
                ('phone_from_invite', models.CharField(max_length=12, unique=True)),
                ('invite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.auth')),
            ],
            options={
                'verbose_name': 'Код подтверждения',
            },
        ),
    ]
