# Generated by Django 4.0.3 on 2022-03-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_auth_my_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default='1q4ST5', max_length=6, unique=True),
        ),
    ]
