# Generated by Django 4.0.3 on 2022-03-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_auth_my_invite_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitecode',
            old_name='invite_code',
            new_name='invitecode',
        ),
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default='kCIDvO', max_length=6, unique=True),
        ),
    ]
