# Generated by Django 4.0.3 on 2022-03-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_invite_code_invitecode_invitecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default='mkgfcj', max_length=6, unique=True),
        ),
    ]
