# Generated by Django 4.0.3 on 2022-03-26 13:46

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_auth_my_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='phone_to_invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_to_invite', to='main.auth'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default='xAg4nj', max_length=6, validators=[main.models.Auth.validate_invitecode]),
        ),
    ]
