# Generated by Django 4.0.3 on 2022-03-26 14:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_invitecode_phone_to_invite_alter_auth_my_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default='DAv4IC', max_length=6, validators=[main.models.Auth.validate_invitecode]),
        ),
    ]
