# Generated by Django 4.0.3 on 2022-03-26 16:29

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_auth_my_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='my_invite_code',
            field=models.CharField(default=main.models.Auth.validate_invitecode, max_length=6),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='phone_to_invite',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
